name: Docker Build and Push with Versioning

on:
  push:
    branches:
      - master  # Trigger workflow on pushes to the master branch

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 for Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build the JAR file with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Get Git commit SHA and timestamp for unique versioning
      - name: Generate Docker Tags
        id: versioning
        run: |
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      # Step 6: Build the Docker image with both tags
      - name: Build Docker Image
        run: |
          docker build -t manyeki/password-generator-app:latest .
          docker tag manyeki/password-generator-app:latest manyeki/password-generator-app:${{ env.sha }}
          docker tag manyeki/password-generator-app:latest manyeki/password-generator-app:${{ env.timestamp }}

      # Step 7: Push the Docker images to DockerHub
      - name: Push Docker Images
        run: |
          docker push manyeki/password-generator-app:latest
          docker push manyeki/password-generator-app:${{ env.sha }}
          docker push manyeki/password-generator-app:${{ env.timestamp }}
