name: Docker Build and Push with Timestamp Tags

on:
  push:
    branches:
      - master  # Trigger workflow on pushes to the master branch

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 for Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build the JAR file with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Generate a timestamp for versioning
      - name: Generate Timestamp
        id: timestamp
        run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      # Step 6: Build the Docker image with a timestamp tag
      - name: Build Docker Image
        run: |
          docker build -t manyeki/password-generator-app:${{ env.timestamp }} .

      # Step 7: Push the Docker image to DockerHub
      - name: Push Docker Image
        run: docker push manyeki/password-generator-app:${{ env.timestamp }}
